spring.application.name=FocusMindAPI

# Configurações de Porta (Padrão 8080 mas garantindo que não colida com React)
server.port=8080

# Configuração do PostgreSQL
# As credenciais reais do banco estão no arquivo application-secret.properties (que foi adicionado ao .gitignore)!
spring.datasource.url=jdbc:postgresql://172.18.16.1:5432/TGFOCUSMIND
spring.datasource.driver-class-name=org.postgresql.Driver

# Importa as configurações do arquivo application-secret.properties
spring.profiles.include=secret

# Configurações do Hibernate (Criação de tabelas automático)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
